### ISSUE TITLE
How to resolve the problem: ImportError: Cannot Import Name version ？

### ISSUE THREAD

**Issue by cddjiang97** [thunlp/OpenNE#105]
jiangjiang@jiangjiangdeMacBook-Pro src % python -m openne --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jiangjiang/Desktop/baseline_code/OpenNE/src/openne/__main__.py", line 7, in <module>
    from . import node2vec
  File "openne/node2vec.py", line 3, in <module>
    from gensim.models import Word2Vec
  File "/Users/jiangjiang/Library/Python/2.7/lib/python/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization, utils  # noqa:F401
  File "/Users/jiangjiang/Library/Python/2.7/lib/python/site-packages/gensim/models/__init__.py", line 23, in <module>
    from . import wrappers  # noqa:F401
  File "/Users/jiangjiang/Library/Python/2.7/lib/python/site-packages/gensim/models/wrappers/__init__.py", line 5, in <module>
    from .ldamallet import LdaMallet  # noqa:F401
  File "/Users/jiangjiang/Library/Python/2.7/lib/python/site-packages/gensim/models/wrappers/ldamallet.py", line 40, in <module>
    from smart_open import smart_open
  File "/Users/jiangjiang/Library/Python/2.7/lib/python/site-packages/smart_open/__init__.py", line 26, in <module>
    from smart_open import version
ImportError: cannot import name version

**Comment by Bznkxs** [comment]
Hi, cddjiang97,
You are using Python 2.7 but Python 3.7 is required.
