### ISSUE TITLE
AttributeError: module 'walker' has no attribute 'Walker'

### ISSUE THREAD

**Issue by hurun** [thunlp/OpenNE#15]
Traceback (most recent call last):
  File "src/main.py", line 128, in <module>
    main(parse_args())
  File "src/main.py", line 84, in main
    workers=args.workers, p=args.p, q=args.q, window=args.window_size)
  File "D:\OpenNE-master\src\libnrl\node2vec.py", line 20, in __init__
    self.walker = walker.Walker(graph, p=p, q=q, workers=kwargs["workers"])
AttributeError: module 'walker' has no attribute 'Walker'

i use py3

**Comment by strange-jiong** [comment]
包导入 改为从顶层开始写 
他原来这个写法比较老

**Comment by hurun** [comment]
well done,copy all files to main derector
