### ISSUE TITLE
Error running LINE 'AttributeError: 'LINE' object has no attribute 'best_vector''

### ISSUE THREAD

**Issue by xinyangz** [thunlp/OpenNE#20]
I got an error when running LINE using the following configuration:
python src/main.py --input graph.txt --graph-format edgelist --representation-size 64 --directed --epochs 20 --method line --no-auto-save --output embed_line_d_64.txt

Traceback (most recent call last):                                                                                     
  File "src/main.py", line 124, in <module>
    main(parse_args())                                                                                                 
  File "src/main.py", line 86, in main                                                                                 
    model = line.LINE(g, epoch = args.epochs, rep_size=args.representation_size, order=args.order)  
  File "/home/xxx/OpenNE/src/libnrl/line.py", line 233, in __init__                                                
    self.vectors = self.best_vector                                                                                   
AttributeError: 'LINE' object has no attribute 'best_vector'

**Comment by zzy14** [comment]
Hi,

Thanks for your issue. I have fixed this bug. 

Please pull the new version.
