### ISSUE TITLE
TADW meeting MemoryError

### ISSUE THREAD

**Issue by RingWong** [thunlp/OpenNE#39]
Hi~!
There is 32G memory in my Ubuntu, I have a graph about 20k vertices and 40k edges. It came up with MemmoryError as following:
```
Traceback (most recent call last):
  File "src/main.py", line 126, in <module>
    main(parse_args())
  File "src/main.py", line 98, in main
    model = tadw.TADW(graph=g, dim=args.representation_size, lamb=args.lamb)
  File "/code/OpenNE/src/libnrl/tadw.py", line 14, in __init__
    self.train()
  File "/code/OpenNE/src/libnrl/tadw.py", line 56, in train
    self.T = self.getT()
  File "/code/OpenNE/src/libnrl/tadw.py", line 39, in getT
    for i in range(g.number_of_nodes())]) 
  File "/home/ring/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError
```
May I have some suggest to handle this problem?

**Comment by zzy14** [comment]
Maybe you can try to implement TADW by scipy.sparse instead of numpy in the matrix operations. If you have any problem with implementing, please let me know.
