### ISSUE TITLE
'DiGraph' object has no attribute 'edges_iter'

### ISSUE THREAD

**Issue by ghost** [thunlp/OpenNE#6]
```
Traceback (most recent call last):
  File "src/main.py", line 124, in <module>
    main(parse_args())
  File "src/main.py", line 74, in main
    g.read_adjlist(filename=args.input)
  File "/home/zhu/Documents/git_repo/OpenNE/src/libnrl/graph.py", line 35, in read_adjlist                                                    
    for i, j in self.G.edges_iter():
AttributeError: 'DiGraph' object has no attribute 'edges_iter'
```

**Comment by zzy14** [comment]
Hi, this bug has been fixed. You can pull again.

**Comment by ghost** [comment]
Thx @zzy14
