### ISSUE TITLE
win10  ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by machineo** [thunlp/OpenNE#73]
Traceback (most recent call last):
  File "D:\aanaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\aanaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python\OpenNE-master\src\openne\__main__.py", line 5, in <module>
    from sklearn.linear_model import LogisticRegression
  File "D:\aanaconda\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "D:\aanaconda\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "D:\aanaconda\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "D:\aanaconda\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "D:\aanaconda\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "D:\aanaconda\lib\site-packages\scipy\sparse\linalg\__init__.py", line 117, in <module>
    from .eigen import *
  File "D:\aanaconda\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "D:\aanaconda\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "D:\aanaconda\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: 找不到指定的程序。

**Comment by jinwuxia** [comment]
Same issue to me. How can I solve it? 
Thanks

**Comment by Bznkxs** [comment]
您好，应该是配置环境时scipy.sparse出现了问题。
